AllCops:
  Exclude:
    # vendor directory is excluded by default.
    - 'vendor/**/*'
    # db/schema.rb is generated automatically.
    - 'db/schema.rb'
Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/BlockAlignment:
  Enabled: false
Lint/DefEndAlignment:
  Enabled: false
# The cop reports not reasonable issues. So, disabled.
# See. http://tech.sideci.com/entry/2016/11/01/105900
Lint/EmptyWhen:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/UnneededDisable:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false

# If AbcSize > 50, really really really really really really really complex
Metrics/AbcSize:
  Max: 50
# Use the default setting
Metrics/BlockNesting:
  Enabled: true
Metrics/BlockLength:
  Max: 30
  Exclude:
    # RuboCop's default
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    # In many cases, config/routes.rb has very long block
    - 'config/routes.rb'
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
# 7 parameters are tooooooo many
Metrics/ParameterLists:
  Enabled: true
  Max: 7
# Use the default setting
Metrics/PerceivedComplexity:
  Enabled: true
# Use the default setting

Performance/RedundantBlockCall:
  Enabled: false

Rails/Delegate:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/PluralizationGrammar:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/ReadWriteAttribute:
  Enabled: false
Rails/RequestReferer:
  Enabled: false
Rails/SafeNavigation:
  Enabled: false

Security/Eval:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
Security/YAMLLoad:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/Alias:
  Enabled: false
Style/AlignArray:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Attr:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/BlockEndNewline:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CaseIndentation:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ClosingParenthesisIndentation:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/CommentIndentation:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/ConstantName:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLineBetweenDefs:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundAccessModifier:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/EndBlock:
  Enabled: false
Style/EndOfLine:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/FileName:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/For:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IndentArray:
  Enabled: false
Style/IndentAssignment:
  Enabled: false
Style/IndentationConsistency:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/InfiniteLoop:
  Enabled: false
Style/InitialIndentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/MethodName:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MultilineArrayBraceLayout:
  Enabled: false
Style/MultilineAssignmentLayout:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineBlockLayout:
  Enabled: false
Style/MultilineHashBraceLayout:
  Enabled: false
Style/MultilineIfThen:
  Enabled: false
Style/MultilineMemoization:
  Enabled: false
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/MultilineMethodDefinitionBraceLayout:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/OpMethod:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/OptionHash:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PredicateName:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantException:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueEnsureAlignment:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/Send:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SpaceAfterColon:
  Enabled: false
Style/SpaceAfterComma:
  Enabled: false
Style/SpaceAfterMethodName:
  Enabled: false
Style/SpaceAfterNot:
  Enabled: false
Style/SpaceAfterSemicolon:
  Enabled: false
Style/SpaceAroundBlockParameters:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/SpaceAroundKeyword:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/SpaceBeforeComma:
  Enabled: false
Style/SpaceBeforeComment:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/SpaceBeforeSemicolon:
  Enabled: false
Style/SpaceInLambdaLiteral:
  Enabled: false
Style/SpaceInsideArrayPercentLiteral:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/SpaceInsideParens:
  Enabled: false
Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Style/SpaceInsideRangeLiteral:
  Enabled: false
Style/SpaceInsideStringInterpolation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StringMethods:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/VariableName:
  Enabled: false
Style/VariableNumber:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
